
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue


  ports:
    - name: http
      port: 8161
      nodePort: 30020
    - name: endpoint
      port: 61616
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  selector:
    app: position-tracker


  ports:
    - name: http
      port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  selector:
    app: api-gateway


  ports:
    - name: http
      port: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: webapp

spec:
  #This defines which pods are going to be represented by the service
  #The service becomes a network endpoint for either other services
  #or maybe external users to connect to (eg browser)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30002

  type: NodePort
